spring:
  application:
    name: HIS-Gateway
server:
  port: 9999
zuul:
  routes:
    his-system:
      path: /user/**
      url: http://localhost:8081/
      strip-prefix: false

logging:
  level:
    com.netflix.zuul: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG
    org.springframework.cloud.netflix.zuul.filters: DEBUG
    org.springframework.cloud.netflix.zuul.filters.route: DEBUG
    com.netflix.ribbon: DEBUG
