global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: "his-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:9999"]

  - job_name: "his-services"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "localhost:8082"
          - "localhost:8083"
          - "localhost:8084"
          - "localhost:8085"
          - "localhost:8086"
          - "localhost:8087"
          - "localhost:8088"
          - "localhost:8089"
          - "localhost:8090"
          - "localhost:8091"
