-- 门诊收费日结单（快照）：生成后写入，核对仅改状态
CREATE TABLE IF NOT EXISTS `bms_daily_settlement` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `operator_id` bigint(20) DEFAULT NULL COMMENT '生成日结的收款员 sms_staff.id',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '收款员姓名（快照）',
  `range_start` datetime NOT NULL COMMENT '统计区间起（含）',
  `range_end` datetime NOT NULL COMMENT '统计区间止（含）',
  `report_time` datetime NOT NULL COMMENT '报表生成时间',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0未核对 1已核对',
  `audit_time` datetime DEFAULT NULL COMMENT '核对时间',
  `auditor_id` bigint(20) DEFAULT NULL COMMENT '核对人',
  `auditor_name` varchar(64) DEFAULT NULL COMMENT '核对人姓名（快照）',
  `amt_registration` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '挂号金额',
  `amt_exam` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '检查金额',
  `amt_lab` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '检验金额',
  `amt_medicine` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '成药金额',
  `amt_herbal` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '草药金额',
  `amt_treatment` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '处置/其它分类金额',
  `amt_total` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '分项合计',
  `pay_cash` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '现金',
  `pay_insurance` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '医保',
  `pay_bank` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '银行卡',
  `pay_alipay` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '支付宝',
  `pay_wechat` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '微信',
  `pay_creditcard` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '信用卡',
  `pay_other` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '其他',
  `pay_channel_total` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '缴费方式合计',
  `invoice_normal` varchar(2000) DEFAULT NULL COMMENT '常规发票号（逗号分隔或说明）',
  `invoice_red` varchar(1000) DEFAULT NULL COMMENT '冲红发票号',
  `invoice_reprint` varchar(1000) DEFAULT NULL COMMENT '重打发票号',
  `remark` varchar(500) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_report_time` (`report_time`),
  KEY `idx_operator` (`operator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门诊收费日结单';
